version: "3"

networks:
  kong-net:
    driver: bridge

services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:1.1.0
    container_name: kong
    restart: always
    networks:
    - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: 123456
      KONG_PROXY_LISTEN: 0.0.0.0:8080
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
    - kong-migration
    links:
    - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
    - "8001:8001"
    - "8080:8080"
    - "8443:8443"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/kong/kong:/opt/kong/kong
