version: "3.5"

networks:
  kong-net:
    driver: bridge
    name: kong-net

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: always
    networks:
    - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: 123456
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.1.0
    container_name: kong-migration
    command: "kong migrations bootstrap"
    networks:
    - kong-net
    restart: on-failure
    environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    - KONG_PG_DATABASE=kong
    - KONG_PG_PASSWORD=123456
    links:
    - kong-database
    depends_on:
    - kong-database

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:0.14.9
    container_name: konga-prepare
    command: "-c prepare -a postgres -u postgresql://kong:123456@kong-database:5432/konga"
    networks:
    - kong-net
    restart: on-failure
    environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    - KONG_PG_DATABASE=konga
    - KONG_PG_PASSWORD=123456
    links:
    - kong-database
    depends_on:
    - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: always
    networks:
    - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:123456@kong-database:5432/konga
      NODE_ENV: production
    links:
    - kong-database
    depends_on:
    - konga-prepare
    ports:
    - "1337:1337"
