version: '3'
networks:
  zookeeper:
services:
  zookeeper1:
    hostname: zookeeper1
    image: zookeeper:3.4.14
    container_name: zookeeper1
    restart: always
    networks:
    - zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888
    volumes:
    - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
#    - /opt/zookeeper/1/data:/data
#    - /opt/zookeeper/1/datalog:/datalog
    ports:
    - "2181:2181"
  zookeeper2:
    hostname: zookeeper2
    image: zookeeper:3.4.14
    container_name: zookeeper2
    restart: always
    networks:
    - zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888
    volumes:
    - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
#    - /opt/zookeeper/2/data:/data
#    - /opt/zookeeper/2/datalog:/datalog
    ports:
    - "2182:2181"